# dataset config : General Recommendation
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id]

data_path: data/processed/MIND_dataset/
benchmark_filename: ['train', 'dev', 'dev']

min_user_inter_num: 10
min_item_inter_num: 10

#enable_amp: True
train_batch_size: 1024
eval_batch_size: 8096
#save_dataloaders: True
#save_dataset: True

latent_dimension: 1024
mlp_hidden_size: [2048]
dropout_prob: 0.5

learning_rate: 0.001
eval_step: 25
epochs: 100
worker: 1

metrics: ['Precision', 'Recall', 'NDCG', 'MAP']
topk: [1, 2, 4, 6, 8, 10]
valid_metric: NDCG@10
eval_args:
    mode: uni10
log_wandb: True
