# dataset config : General Recommendation
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, label]
    item:  [item_id, 'embedding']

numerical_features: ['embedding']

data_path: data/processed/MIND_dataset/
benchmark_filename: ['train', 'dev', 'dev']

worker: 6

# Training and evaluation config
train_batch_size: 8192
lr: 0.1
eval_step: 50
epochs: 300

metrics: ['Precision', 'Recall', 'NDCG', 'MAP']
topk: [1, 2, 4, 6, 8, 10]
valid_metric: NDCG@10
eval_args:
    mode: uni10
log_wandb: True
